title: 'Toxidromes by Vital Signs'
authors:
    - 'Michelle Lin, MD'
created: 2010/11/19
updates: null
categories:
    - Toxicology
drugs: 'propranolol, propoxyphene, physostigmine, clonidine, digoxin, theophylline, clonidine, aminophylline,'
