title: 'Neutropenic Fever and Cancer'
authors:
    - 'Michelle Lin, MD'
created: 2011/10/07
updates: null
categories:
    - 'Hematology and Oncology'
drugs: 'ciprofloxacin, vancomycin, cefipime, pipercillin-tazobactam, amoxicillin-clavulanate, aztreonam'
