language: node_js
node_js:
    - node
branches:
    only:
        - master
        - /^greenkeeper-.*$/
        - /^v\d+\.\d+\.\d+(?:-rc\d+)?/
dist: trusty
cache:
  directories:
    - "node_modules"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libjpeg-dev libpng12-0
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
script: npm run test -- --coverage && npm run build
before_deploy:
    - npm run s3
deploy:
    'on':
        tags: true
    skip_cleanup: true
    provider: script
    script: ./deploy
after_success:
    - bash <(curl -s https://codecov.io/bash)
