language: node_js
node_js:
    - node
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache: yarn
after_success:
    - yarn build
    - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy
