language: node_js
node_js:
    - node
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache: yarn
before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
script: yarn test && yarn build
after_success:
    - bash <(curl -s https://codecov.io/bash)
before_deploy:
    - yarn s3
deploy:
    on:
        tags: true
    skip_cleanup: true
    provider: script
    script: ./deploy
