title: 'Emergency Drug Card - Adult'
authors:
    - 'Rob Bryant, MD'
    - 'Amie Hatch, PharmD, BCPS'
    - 'Jeremy Bair, PharmD'
created: 2013/09/11
updates: null
categories:
    - Pharmacology
    - 'Critical Care'
drugs: 'etomidate, lidocaine, rocuronium, succinylcholine, vecuronium, amiodarone, diltiazem, esmolol, labetalol, nicardipine, procainamide, fentanyl, ketamine, propofol, dobutamine, dopamine, epinephrine, norepinephrine, phenylephrine, vasopressin'
