title: 'Vasopressors in Hypotension'
authors:
    - 'Todd A. Seigel, MD'
created: 2013/08/20
updates: null
categories:
    - 'Critical Care'
    - Cardiovascular
drugs: 'dobutamine, isoproterenol, epinephrine, norepinephrine, dopamine'
