title: 'Pediatric Ingestion Dose Thresholds for ED Referral'
authors:
    - 'Bryan D. Hayes, PharmD'
created: 2014/07/09
updates: null
categories:
    - Pediatrics
    - Toxicology
drugs: 'acetaminophen, aripiprazole, clozapine, olanzapine, quetiapine, risperidone, ziprasidone, acebutolol, atenolol, carvedilol, labetalol, metoprolol, nadolol, propranolol, sotalol, timolol, amlodipine, diltiazem, felodipine, isradipine, nifedipine, verapamil, camphor, dextromethorphan, diphenhydramine, dimenhydrinate, ethylene glycol, iron, mercury, methylphenidate, salicylate, aspirin, citalopram, escitalopram, fluoxetine, fluvoxamine, paroxetine, sertraline, desipramine, nortriptyline, trimipramine, protriptyline, valproic acid'
