title: 'Bicarbonate - Completely Useless?'
authors:
    - 'Andrew Grock, MD'
created: 2013/12/04
updates: null
categories:
    - Toxicology
    - Pharmacology
    - 'Critical Care'
drugs: 'sodium bicarbonate'
