title: 'Continuous Infusions'
authors:
    - 'Michelle Lin, MD'
created: 2012/03/09
updates: null
categories:
    - Pharmacology
    - 'Critical Care'
drugs: 'amiodarone, Diltiazem, Dobutamine, Dopamine, Epinephrine, Esmolol, fentanyl, furosemide, Isoproterenol, ketamine, lidocaine, Lorazepam, midazolam, naloxone, Nicardipine, Nitroglycerin, Nitroprusside, Norepinephrine, Octreotide, Phenylephrine, propofol, Vasopressin, Vecuronium'
