title: 'Emergency Drug Card (Pediatric)'
authors:
    - 'Rob Bryant, MD'
    - 'Amie Hatch, PharmD, BCPS'
    - 'Jeremy Bair, PharmD'
created: 2013/09/11
updates: null
categories:
    - Pharmacology
    - 'Critical Care'
drugs: 'adenosine, amiodarone, atronie, calcium chloride, dextrose, epinephrine, Magnesium, procainamide, sodium bicarbonate, etomidate, lidocaine, rocuronium, succinylcholine, vecuronium, Haloperidol, dobutamine, dopamine, norepinephrine, phenylephrine, vasopressin, Diazepam, Fosphenytoin, Levetiracetam, Lorazepam, Midazolam, Phenobarbital, Nitroglycerin, Nitroprusside, Dexamethasone, Diphenhydramine, Famotidine, Methylprednisolone, Ranitidine, fentanyl, ketamine, propofol, morphine, N-acetylcysteine, Flumazenil, Fomepizole, Naloxone, Alprostadil, prostaglandin, factor VIII, heparin, Ondansetron'
