title: 'Ultrasound DVT Assessment'
authors:
    - 'Margaret Greenwood-Ericksen, MD'
    - 'Joshua Rempell, MD'
    - 'Mike Stone, MD'
created: 2015/02/18
updates: null
categories:
    - Radiology
    - Ultrasound
    - Cardiovascular
drugs: null
