title: 'Testicular Ultrasound Assessment'
authors:
    - 'Matthew Dawson, MD'
    - 'Mike Stone, MD'
created: 2015/01/21
updates: null
categories:
    - Genitourinary
    - Radiology
    - Ultrasound
drugs: null
