title: 'Benzodiazepines Metabolism by the Liver'
authors:
    - 'Brian Hayes, PharmD'
created: 2013/11/13
updates: null
categories:
    - Pharmacology
    - Toxicology
drugs: 'lorazepam, oxazepam, temazepam, clonazepam, midazolam, diazepam'
