title: 'Influenza - to treat or not to treat?'
authors:
    - 'Michelle Lin, MD'
created: 2011/10/28
updates: null
categories:
    - 'Infectious Disease'
drugs: 'Amantadine, Rimantidine, Oseltamivir, Zanamivir'
