title: 'Procedural Sedation & Analgesia'
authors:
    - 'Demian Szyld, MD'
created: 2010/08/06
updates: null
categories:
    - Pharmacology
    - Procedures
drugs: 'propofol, etomidate, ketamine, ketofol, Dexamedetomidine, lorazepam, diazepam, midazolam, Fentanyl, Hydromorphone, Morphine'
