title: 'Focused Biliary Assessment'
authors:
    - 'John Eicken, MD'
    - 'Mike Stone, MD'
created: 2015/01/01
updates: null
categories:
    - Radiology
    - Ultrasound
    - Gastroenterology
drugs: null
