title: 'Thrombolytics for Submassive PE'
authors:
    - 'Hans Rosenberg, MD'
created: 2011/07/29
updates: null
categories:
    - 'Critical Care'
    - Pulmonology
drugs: 'tPA, tenecteplase, alteplase, heparin'
