title: 'Serotonin Syndrome'
authors:
    - 'Michelle Lin, MD'
created: 2012/01/06
updates: null
categories:
    - Toxicology
drugs: 'Cyclobenzaprine, Fentanyl, Meperidine, Tramadol, Buspirone, Lithium, Metoclopramide, Ondansetron, Carbamazepine, valproic acid, cocaine, Dextromethorphan, Linezolid, cyproheptadine'
