title: 'Vasopressors and Inotropes in Shock'
authors:
    - 'Michelle Lin, MD'
created: 2010/04/30
updates: null
categories:
    - Cardiovascular
    - 'Critical Care'
drugs: 'epinephrine, Phenylephrine, norepinephrine, dopamine, dobutamine'
