title: 'Fever Without a Source - neonate'
authors:
    - 'Michelle Lin, MD'
created: 2012/02/02
updates: null
categories:
    - Pediatrics
    - 'Infectious Disease'
drugs: 'Ampicillin, Cefotaxime, Gentamicin'
