title: 'NSAIDs and Upper GI Bleed'
authors:
    - 'Michelle Lin, MD'
created: 2011/07/15
updates: null
categories:
    - Gastroenterology
    - Pharmacology
drugs: 'Ibuprofen, Diclofenac, Meloxicam, Indomethacin, Ketoprofen, Naproxen, Piroxicam, Ketorolac, Celecoxib, Aceclofenac, Rofecoxib'
